// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu_FciDwgtZEmNeECsofX0zuixrG_5QwA',
    appId: '1:314190526828:web:9c861587583238f2f51b49',
    messagingSenderId: '314190526828',
    projectId: 'ecom-v2-pro',
    authDomain: 'ecom-v2-pro.firebaseapp.com',
    storageBucket: 'ecom-v2-pro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8m-hPa-T9HYRK0xekf2Ey4aSzlD175wA',
    appId: '1:314190526828:android:43821e6ebe58fd65f51b49',
    messagingSenderId: '314190526828',
    projectId: 'ecom-v2-pro',
    storageBucket: 'ecom-v2-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD0z_TnWgsgq-m6u740sYyN58Yyq6_ebk',
    appId: '1:314190526828:ios:f39e86e74de4e004f51b49',
    messagingSenderId: '314190526828',
    projectId: 'ecom-v2-pro',
    storageBucket: 'ecom-v2-pro.appspot.com',
    iosClientId: '314190526828-28ch2n1ad7n9i82afacgep8ep8p6ob8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD0z_TnWgsgq-m6u740sYyN58Yyq6_ebk',
    appId: '1:314190526828:ios:aaf922f7e9f13938f51b49',
    messagingSenderId: '314190526828',
    projectId: 'ecom-v2-pro',
    storageBucket: 'ecom-v2-pro.appspot.com',
    iosClientId: '314190526828-gl2gb2kns2ni3o8u2nv1bqfa1hp63v23.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
